# docker-compose file only intended for development

version: '3'
services:
  postgres:
    image: postgres:13.2
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  redis:
    image: redis:6.2.3
    ports:
      - 6379:6379
      - 6380:6379
volumes:
  postgres-data: